# This Docker Compose file defines the core infrastructure services for Avina.
# It should be run alongside docker-compose.apps.yml

services:
  nginx:
    build:
      context: ./nginx
    container_name: avina-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/${NGINX_CONFIG_FILE}:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/private
      - ./static:/var/www/static_html:ro # Optional: for serving static content
    networks:
      - app_network
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: avina-mongodb
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    volumes:
      - ./data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DATABASE}"
    command: ["mongod", "--auth", "--bind_ip_all"]
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
    # The network name is now dynamically generated by Docker Compose based on COMPOSE_PROJECT_NAME
    # This allows QA and Prod environments to run on the same host without network conflicts.
